arch_betavae: True
loss_reconstruction: mse

factor_names:
  - floor_color
  - wall_color
  - object_color

train_size: 20000
n_labels_per_factor: 1000

factor_dim: 1
residual_dim: 7

residual_std: 1

train:
  batch_size: 128
  n_epochs: 200
  n_epochs_between_evals: 50
  n_epochs_between_visualizations: 10
  n_epochs_before_entropy: 20

  learning_rate:
    latent: 0.01
    classifier: 0.0001
    generator: 0.001
    min: 0.0001

  loss_weights:
    reconstruction: 1
    residual_decay: 0.00001

    entropy: 0.001
    classification: 0.001
    supervised: 10

amortization:
  batch_size: 128
  n_epochs: 50
  n_epochs_between_evals: 25
  n_epochs_between_visualizations: 10

  learning_rate:
    max: 0.001
    min: 0.00001

synthesis:
  batch_size: 128
  n_epochs: 50
  n_epochs_between_evals: 25
  n_epochs_between_visualizations: 10

  adversarial: False

  learning_rate:
    generator: 0.0001

  loss_weights:
    reconstruction: 1
    latent: 10

gt_labels: True
